# -*- mode: ruby -*-
# vi: set ft=ruby :

IP_SERVER = '192.168.56.110'
IP_WORKER = '192.168.56.111'
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	# What box is used for the create the VM
	config.vm.box = "hashicorp/bionic64"
	config.vm.box_version = "1.0.282"

	# Define the VM's configs
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 2
	end

	# Config mravilyServer vagrant box
	config.vm.define "mravilyS" do |mravilyS|
		# Change the hostname
		mravilyS.vm.hostname = "mravilyS"
		# Setup the private network with the hostname and selected ip
		mravilyS.vm.network "private_network", hostname: true, ip: IP_SERVER
		# Disable the automatic vagrant replace pair keys
		mravilyS.ssh.insert_key = false
		# Overide Authorized Keys File
		mravilyS.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "confs/id_rsa"]
		# Add the public key to authorized keys
		mravilyS.vm.provision "file", source: "confs/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		# Private Key Provisioning
		mravilyS.vm.provision "file", source: "confs/id_rsa", destination: "~/.ssh/id_rsa"
		# Public Key Provisioning
		mravilyS.vm.provision "file", source: "confs/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		# Provisioning and execute script	
		mravilyS.vm.provision "shell", path: "scripts/server.sh", args: [IP_SERVER]
	end

	# Config mravilyServerWorker vagrant box
	config.vm.define "mravilySW" do |mravilySW|
		# Change the hostname
		mravilySW.vm.hostname = "mravilySW"
		# Disable the automatic vagrant replace pair keys
		mravilySW.ssh.insert_key = false
		# Setup the private network with the hostname and selected ip
		mravilySW.vm.network "private_network", hostname: true, ip: IP_WORKER
		# Add the public key to authorized keys
		mravilySW.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "confs/id_rsa"]
		# Add the public key to authorized keys
		mravilySW.vm.provision "file", source: "confs/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		# Private Key Provisioning
		mravilySW.vm.provision "file", source: "confs/id_rsa", destination: "~/.ssh/id_rsa"
		# Public Key Provisioning
		mravilySW.vm.provision "file", source: "confs/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		# Provisioning and execute script
		mravilySW.vm.provision "shell", path: "scripts/worker.sh", args: [IP_SERVER, IP_WORKER]
	end
end
