# -*- mode: ruby -*-
# vi: set ft=ruby :

IP_NODE = '192.168.56.113'
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	# What box is used for the create the VM
	config.vm.box = "ubuntu/focal64"

	# Define the VM's configs
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 10000
		vb.cpus = 5
		vb.name = "p3"
	end

	# Config p3 VM vagrant box
	config.vm.define "p3" do |p3|
		# Change the hostname
		p3.vm.hostname = "p3"
		# Setup the private network with the hostname and selected ip
		p3.vm.network "private_network", hostname: true, ip: IP_NODE
	# Disable the automatic vagrant replace pair keys
		p3.ssh.insert_key = false
		# Add the public key to authorized keys
		p3.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		# # Private Key Provisioning
		# # Public Key Provisioning
		# p3.vm.provision "file", source: "confs/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		p3.vm.provision "file", source: "confs/mravily-argo-cd", destination: "~/argo-cd"
		p3.vm.provision "file", source: "scripts/", destination: "~/scripts"
		p3.vm.provision "shell", path: "scripts/config-vm.sh"
	end
end